name: xfrpc 

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
    
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install other depend lib
      run: |
          sudo apt-get update -y
          sudo apt-get install -y libjson-c-dev
          sudo apt-get install -y libevent-dev
          
    - name: compile xfrpc
      run: |
        mkdir build
        cd build
        cmake ..
        make
        tar -cvf xfrp.tar xfrp
        cd xfrp
        ls -lh
        
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
    with:
    args: xfrp.tar application/zip
     env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        
        
