name: xfrpc 

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
    
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install other depend lib
      run: |
          sudo apt-get update -y
          sudo apt-get install -y libjson-c-dev
          sudo apt-get install -y libevent-dev
          
    - name: compile xfrpc
      run: |
        mkdir build
        cd build
        cmake ..
        make
        echo xxm
        pwd 
        # /home/runner/work/xfrpc/xfrpc/build
        #find / -name xfrp*
        # /home/runner/work/_PipelineMapping/90999/xfrpc
        # /home/runner/work/xfrpc
        # /home/runner/work/xfrpc/xfrpc
        # /home/runner/work/xfrpc/xfrpc/build/xfrpc
        
        cd ../../../
        pwd
        tar -cvf xfrp.tar xfrpc
        echo xxm finish

       
